// v2026.7.1 OpenClaw parity mirror of test/scripts/plugin-package-dependencies.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [test/scripts/plugin-package-dependencies.test.ts:25] extracts dependency package names from bare import specifiers",
          "[v7_1][parity_gap]") {
    PARITY_GAP("test/scripts/plugin-package-dependencies.test.ts:25",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [test/scripts/plugin-package-dependencies.test.ts:36] collects only runtime dependency specs from package manifests",
          "[v7_1][parity_gap]") {
    PARITY_GAP("test/scripts/plugin-package-dependencies.test.ts:36",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [test/scripts/plugin-package-dependencies.test.ts:57] collects bundled plugin dependency owners and conflicts deterministically",
          "[v7_1][parity_gap]") {
    PARITY_GAP("test/scripts/plugin-package-dependencies.test.ts:57",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
