// v2026.7.1 OpenClaw parity mirror of src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:29] returns a friendly message for context overflow",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:29",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:33] returns context overflow for Anthropic ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:33",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:41] returns context overflow for Kimi ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:41",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:47] returns context overflow for Ollama ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:47",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:53] returns a reasoning-required message for mandatory reasoning endpoint errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:53",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:62] returns a friendly message for Anthropic role ordering",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:62",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:66] returns a friendly message for Anthropic overload errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:66",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:74] preserves overload wording for Z.AI rate-limit errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:74",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:82] rewrites generic provider internal errors without support request ids",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:82",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:90] rewrites request-id-only generic provider internal errors without exposing the id",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:90",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:98] returns a model-switch hint for OpenAI model capacity errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:98",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:104] returns a recovery hint when tool call input is missing",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:104",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:110] returns a recovery hint for replay-invalid connection mismatch errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:110",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:116] handles JSON-wrapped role errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:116",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:122] suppresses raw error JSON payloads that are not otherwise classified",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:122",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:128] classifies provider upstream_error payloads as server errors for fallback",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:128",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:143] uses generic user-facing copy for escaped structured provider messages",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:143",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:154] sanitizes Codex error-prefixed JSON payloads",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:154",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:160] returns a friendly billing message for credit balance errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:160",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:165] returns a friendly billing message for HTTP 402 errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:165",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:170] returns a friendly billing message for insufficient credits",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:170",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:175] includes provider and assistant model in billing message when provider is given",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:175",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:182] uses the active assistant model for billing message context",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:182",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:188] returns generic billing message when provider is not given",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:188",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:194] returns a friendly billing message for flat JSON insufficient_balance payloads (#74079)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:194",
               "upstream it() block #24",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:204] returns a billing message for xAI 429 credit exhaustion before rate-limit copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:204",
               "upstream it() block #25",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:216] keeps known Moonshot 429 balance failures on billing copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:216",
               "upstream it() block #26",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:226] keeps high-confidence 429 insufficient quota failures on billing copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:226",
               "upstream it() block #27",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:236] keeps high-confidence 429 insufficient balance failures on billing copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:236",
               "upstream it() block #28",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:246] keeps structured 429 insufficient balance codes on billing copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:246",
               "upstream it() block #29",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:256] keeps 429 more-credits failures on billing copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:256",
               "upstream it() block #30",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:264] keeps OpenRouter 429 key budget failures on billing copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:264",
               "upstream it() block #31",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:272] returns billing guidance for Volcengine Coding Plan subscription failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:272",
               "upstream it() block #32",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:282] returns a friendly message for rate limit errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:282",
               "upstream it() block #33",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:286] keeps plain HTTP rate-limit guidance user-facing",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:286",
               "upstream it() block #34",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:292] surfaces provider-specific rate limit message with reset time (#54433)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:292",
               "upstream it() block #35",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:302] surfaces provider-specific rate limit message from JSON payload (#54433)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:302",
               "upstream it() block #36",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:312] returns generic rate limit message when no specific details are present",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:312",
               "upstream it() block #37",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:319] strips leading HTTP status code prefix from non-JSON rate limit messages",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:319",
               "upstream it() block #38",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:327] returns upstream HTML copy for HTML quota pages",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:327",
               "upstream it() block #39",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:336] returns upstream HTML copy for prefixed 521 HTML rate-limit pages",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:336",
               "upstream it() block #40",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:345] does not misdiagnose standalone Cloudflare challenge HTML as DNS",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:345",
               "upstream it() block #41",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:362] returns a friendly message for empty stream chunk errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:362",
               "upstream it() block #42",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:367] returns a connection-refused message for ECONNREFUSED failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:367",
               "upstream it() block #43",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:384] returns a DNS-specific message for provider lookup failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:384",
               "upstream it() block #44",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:391] returns an interrupted-connection message for socket hang ups",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:391",
               "upstream it() block #45",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:398] returns an explicit re-authentication message for OAuth refresh failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:398",
               "upstream it() block #46",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:407] returns an explicit re-authentication message for Codex app-server refresh failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:407",
               "upstream it() block #47",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:416] returns a contention-specific message for OAuth refresh lock timeouts",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:416",
               "upstream it() block #48",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:423] returns a timeout-specific message for OAuth refresh hard timeouts",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:423",
               "upstream it() block #49",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:432] returns a missing-scope message for OpenAI ChatGPT scope failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:432",
               "upstream it() block #50",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:441] returns a missing-scope message for raw OpenAI ChatGPT scope payloads without an HTTP prefix",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:441",
               "upstream it() block #51",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:450] does not misdiagnose other provider permission errors as OpenAI scope failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:450",
               "upstream it() block #52",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:459] does not misdiagnose generic OpenAI permission failures as missing-scope failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:459",
               "upstream it() block #53",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:468] returns re-authentication copy for HTML provider 401 auth failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:468",
               "upstream it() block #54",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:475] returns re-authentication copy for HTML provider 403 auth failures",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:475",
               "upstream it() block #55",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:482] sanitizes raw HTTP 401 / Invalid token errors into a re-auth hint (#56197)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:482",
               "upstream it() block #56",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:489] sanitizes Unauthorized / token-expired variants under HTTP 401",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:489",
               "upstream it() block #57",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:503] does not collapse 401 billing / permanent-auth errors into the generic re-auth hint",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:503",
               "upstream it() block #58",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:511] does not claim HTTP 401 for plain 403 errors that fall through to the generic auth reason (#77394 review)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:511",
               "upstream it() block #59",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:519] does not claim HTTP 401 for message-only auth errors with no HTTP status prefix (#77394 review)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:519",
               "upstream it() block #60",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:527] does not rewrite provider-less missing-scope 401 payloads as invalid-token errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:527",
               "upstream it() block #61",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:540] returns a proxy-specific message for proxy misroutes",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:540",
               "upstream it() block #62",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:547] keeps non-transport config errors that mention proxy settings actionable",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:547",
               "upstream it() block #63",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:559] sanitizes invalid streaming event order errors",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:559",
               "upstream it() block #64",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:568] sanitizes transport-classified malformed streaming fragments (#59076)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:568",
               "upstream it() block #65",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:575] does not broadly rewrite non-streaming ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:575",
               "upstream it() block #66",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:580] does not rewrite non-streaming provider JSON request-validation diagnostics",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:580",
               "upstream it() block #67",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:587] keeps provider request-validation JSON diagnostics actionable",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:587",
               "upstream it() block #68",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:599] uses structured error body detail for model-not-found copy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:599",
               "upstream it() block #69",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:618] renders HTTP code + type + message from Anthropic payloads",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:618",
               "upstream it() block #70",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:629] renders a generic unknown error message when raw is empty",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:629",
               "upstream it() block #71",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:633] formats plain HTTP status lines",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:633",
               "upstream it() block #72",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:639] formats colon-delimited HTTP status lines",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:639",
               "upstream it() block #73",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:643] formats plain provider internal errors without request ids",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:643",
               "upstream it() block #74",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:651] sanitizes HTML error pages into a clean unavailable message",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:651",
               "upstream it() block #75",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:663] formats standalone Cloudflare challenge HTML into a clean provider error",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:663",
               "upstream it() block #76",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:678] truncates fallback raw error text on UTF-16 code-point boundary without dangling surrogates",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:678",
               "upstream it() block #77",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:707] recognizes provider-prefixed JSON payloads for observation fingerprints",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:707",
               "upstream it() block #78",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:717] recognizes flat JSON payloads with string error code and message (#74079)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:717",
               "upstream it() block #79",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:729] returns neutral copy for oauth authMode — no ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:729",
               "upstream it() block #80",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:736] returns neutral copy for token authMode — no ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:736",
               "upstream it() block #81",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:742] REGRESSION: api_key authMode still returns ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:742",
               "upstream it() block #82",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:748] REGRESSION: undefined authMode (legacy call-sites) still returns ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:748",
               "upstream it() block #83",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:753] REGRESSION: no-provider call still returns generic ",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:753",
               "upstream it() block #84",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:760] rewrites transport-classified malformed streaming fragments in error context",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:760",
               "upstream it() block #85",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:767] does not rewrite JSON parse error when not in error context",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-helpers.formatassistanterrortext.test.ts:767",
               "upstream it() block #86",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
