// v2026.7.1 OpenClaw parity mirror of src/agents/tool-catalog.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/agents/tool-catalog.test.ts:25] includes code_execution, web_search, x_search, web_fetch, and update_plan in the coding profile policy",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/tool-catalog.test.ts:25",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/tool-catalog.test.ts:61] includes bundle MCP tools in coding and messaging profile policies",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/tool-catalog.test.ts:61",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/tool-catalog.test.ts:74] full profile uses wildcard to grant all tools (#76507)",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/tool-catalog.test.ts:74",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
