// v2026.7.1 OpenClaw parity mirror of src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../../parity.hpp"

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:7] keeps compact visible names separate from replay-safe names",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:7",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:44] counts explicitly allowlisted client tools before they are cataloged later",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:44",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:66] keeps code-mode control tools in replay-safe names",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:66",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:84] does not let unrelated client tools mask a bad explicit allowlist",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:84",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:106] keeps explicitly requested Tool Search controls callable",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:106",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:119] keeps uncataloged directory-mode client tools visible",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:119",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:161] does not let visible directory client tools mask a bad explicit allowlist",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:161",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:190] counts explicitly allowlisted visible directory client tools",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:190",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:218] counts wildcard-allowlisted visible directory client tools",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:218",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:246] keeps client names out of OpenClaw capability guidance",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:246",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:269] keeps MCP names out of OpenClaw capability guidance",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:269",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:294] keeps ambiguous deferred directory names out of live calls",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/embedded-agent-runner/run/attempt.tool-search-run-plan.test.ts:294",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
