// v2026.7.1 OpenClaw parity mirror of extensions/voice-call/src/webhook.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:225] auto-selects the first registered provider when streaming.provider is unset",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:225",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:270] records media stream Talk events on the active call metadata",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:270",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:360] uses forwarded IPs only when forwarding trust is explicitly enabled",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:360",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:379] does not trust forwarded IPs when only allowedHosts is configured",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:379",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:399] ignores spoofed forwarded IPs from untrusted remotes",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:399",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:419] walks the forwarded chain from the right to support trusted multi-proxy deployments",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:419",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:438] ignores forwarded IPs when no trusted proxy is configured",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:438",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:459] matches trusted proxies when the remote uses an IPv4-mapped form",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:459",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:681] does not route sibling paths through the realtime stream handler",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:681",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:698] routes root stream child paths through the realtime stream handler",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:698",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:721] ends calls older than staleCallReaperSeconds",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:721",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:730] skips calls that are younger than the threshold",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:730",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:739] does not run when staleCallReaperSeconds is disabled",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:739",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:757] does not reap calls that reached the answered state",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:757",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:772] rejects lookalike webhook paths that only match by prefix",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:772",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:803] matches webhook paths without trusting malformed Host headers",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:803",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:855] acknowledges replayed webhook requests and skips event side effects",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:855",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:893] does not cache replay responses when the TTL would exceed the Date range",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:893",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:927] returns Plivo XML for replayed answer callbacks while skipping event side effects",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:927",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:987] does not return realtime TwiML for replayed inbound twilio webhooks",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:987",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1157] does not let real Twilio provider parsing mint stream state for replayed realtime requests",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1157",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1218] serves initial provider TwiML before the realtime shortcut",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1218",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1283] rejects non-allowlisted inbound realtime calls before creating a stream token",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1283",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1335] creates a realtime stream only for allowlisted inbound callers",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1335",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1387] passes verified request key from verifyWebhook into parseWebhookEvent",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1387",
               "upstream it() block #24",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1438] rejects requests when verification succeeds without a request key",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1438",
               "upstream it() block #25",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1462] rejects missing signature headers before reading the request body",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1462",
               "upstream it() block #26",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1489] uses the shared pre-auth body cap before verification",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1489",
               "upstream it() block #27",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1517] limits concurrent pre-auth requests per source IP",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1517",
               "upstream it() block #28",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1581] limits missing remote addresses with a shared fallback bucket",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1581",
               "upstream it() block #29",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1662] keeps outbound calls on their frozen agent when the dialed number has an inbound route",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1662",
               "upstream it() block #30",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1708] does not replay a completed response after early playback",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1708",
               "upstream it() block #31",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1744] preserves explicit empty provider response bodies",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1744",
               "upstream it() block #32",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1770] returns existing URL when start() is called twice without stop()",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1770",
               "upstream it() block #33",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1790] supports concurrent start() calls without double-binding the port",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1790",
               "upstream it() block #34",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1805] can start again after stop()",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1805",
               "upstream it() block #35",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1820] stop() is safe to call when server was never started",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1820",
               "upstream it() block #36",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1838] ignores stale stream disconnects after reconnect and only hangs up on current stream disconnect",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1838",
               "upstream it() block #37",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1935] logs streaming transcripts without splitting UTF-16 surrogate pairs",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1935",
               "upstream it() block #38",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:1977] suppresses barge-in clear while outbound conversation initial message is pending",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:1977",
               "upstream it() block #39",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:2068] keeps barge-in clear enabled for inbound calls",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:2068",
               "upstream it() block #40",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/voice-call/src/webhook.test.ts:2199] auto-responds to a final inbound webhook transcript",
          "[v7_1][parity_gap][voice-call]") {
    PARITY_GAP("extensions/voice-call/src/webhook.test.ts:2199",
               "upstream it() block #41",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
