// v2026.5.2 OpenClaw parity mirror of src/commands/openai-model-default.test.ts
//
// Auto-generated by tests/v5_2/generate.py from the openclaw v2026.5.2
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v5.2 [src/commands/openai-model-default.test.ts:25] sets defaults when model is unset",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/openai-model-default.test.ts:25",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/openai-model-default.test.ts:31] overrides existing models",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/openai-model-default.test.ts:31",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/openai-model-default.test.ts:39] no-ops when already legacy opencode-zen default",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/openai-model-default.test.ts:39",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/openai-model-default.test.ts:47] preserves fallbacks when setting primary",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/openai-model-default.test.ts:47",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/openai-model-default.test.ts:66] no-ops when already on the current default",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/openai-model-default.test.ts:66",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
