// v2026.5.2 OpenClaw parity mirror of extensions/telegram/src/bot-update-tracker.test.ts
//
// Auto-generated by tests/v5_2/generate.py from the openclaw v2026.5.2
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v5.2 [extensions/telegram/src/bot-update-tracker.test.ts:26] persists accepted offsets before earlier pending updates complete",
          "[v5_2][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/bot-update-tracker.test.ts:26",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/telegram/src/bot-update-tracker.test.ts:65] skips restart replays once the accepted offset is restored",
          "[v5_2][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/bot-update-tracker.test.ts:65",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/telegram/src/bot-update-tracker.test.ts:86] serializes and coalesces accepted offset persistence",
          "[v5_2][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/bot-update-tracker.test.ts:86",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/telegram/src/bot-update-tracker.test.ts:128] keeps failed accepted updates retryable in the same process",
          "[v5_2][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/bot-update-tracker.test.ts:128",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/telegram/src/bot-update-tracker.test.ts:161] dedupes handler dispatch separately from the accepted watermark",
          "[v5_2][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/bot-update-tracker.test.ts:161",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
