// v2026.7.1 OpenClaw parity mirror of src/auto-reply/reply/commands-acp/context.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../../parity.hpp"

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:409] resolves channel/account/thread context from originating fields",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:409",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:428] resolves discord DM current conversation ids from direct sender context",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:428",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:447] resolves discord thread parent from ParentSessionKey when targets point at the thread",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:447",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:467] resolves discord thread parent from native context when ParentSessionKey is absent",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:467",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:487] falls back to default account and target-derived conversation id",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:487",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:504] uses the plugin default account when ACP context omits AccountId",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:504",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:556] builds canonical telegram topic conversation ids from originating chat + thread",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:556",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:575] resolves Telegram DM conversation ids from telegram targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:575",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:592] resolves LINE DM conversation ids from raw LINE targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:592",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:609] resolves LINE conversation ids from prefixed LINE targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:609",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:626] resolves LINE conversation ids from canonical line targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:626",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:644] resolves Matrix thread context from the current room and thread root",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:644",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:664] resolves iMessage DM conversation ids from current targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:664",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:682] resolves iMessage group conversation ids from explicit chat targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:682",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:701] resolves iMessage group conversation ids from chat_id targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:701",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:720] builds Feishu topic conversation ids from chat target + root message id",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:720",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:741] builds sender-scoped Feishu topic conversation ids when current session is sender-scoped",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:741",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:767] preserves sender-scoped Feishu topic ids after ACP route takeover via ParentSessionKey",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:767",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:790] preserves sender-scoped Feishu topic ids after ACP takeover from the live binding record",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:790",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:827] resolves Feishu DM conversation ids from user targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:827",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:845] resolves Feishu DM conversation ids from user_id fallback targets",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:845",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-acp/context.test.ts:863] does not infer a Feishu DM parent conversation id during fallback binding lookup",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-acp/context.test.ts:863",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
