// v2026.7.1 OpenClaw parity mirror of src/process/exec.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/process/exec.test.ts:109] never enables shell execution (Windows cmd.exe injection hardening)",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:109",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:118] merges custom env with base env and drops undefined values",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:118",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:136] collapses case-insensitive duplicate env keys on Windows",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:136",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:156] preserves case-distinct env keys outside Windows",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:156",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:172] suppresses npm fund prompts for npm argv",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:172",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:182] caps oversized execFile timeouts",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:182",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:199] infers success for shimmed Windows commands when exit codes are missing",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:199",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:213] does not infer success when this process already issued a timeout kill",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:213",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:227] does not spawn when the abort signal is already aborted",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:227",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:349] does not crash when stdout or stderr emit an error event",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:349",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:363] preserves matching output lines even when the tail capture truncates them",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:363",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:388] bounds preserved matching output for long lines without newlines",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:388",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:404] keeps preserved line tails on a UTF-8 boundary",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:404",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/process/exec.test.ts:427] forwards SIGTERM to the wrapped child and detaches on exit",
          "[v7_1][parity_gap][process]") {
    PARITY_GAP("src/process/exec.test.ts:427",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
