// v2026.7.1 OpenClaw parity mirror of extensions/browser/src/cli/browser-cli-extension.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../../parity.hpp"

TEST_CASE("v7.1 [extensions/browser/src/cli/browser-cli-extension.test.ts:13] builds the direct relay route and preserves a proxy base path",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/cli/browser-cli-extension.test.ts:13",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/cli/browser-cli-extension.test.ts:22] allows plaintext WebSockets only on loopback",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/cli/browser-cli-extension.test.ts:22",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/cli/browser-cli-extension.test.ts:29] rejects non-WebSocket and ambiguous credential-bearing URLs",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/cli/browser-cli-extension.test.ts:29",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/cli/browser-cli-extension.test.ts:43] resolves the copied extension from the registered plugin root",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/cli/browser-cli-extension.test.ts:43",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
