// v2026.7.1 OpenClaw parity mirror of src/infra/exec-approval-reply.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:89] returns the approver DM notice text",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:89",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:95] mentions Matrix in the fallback native approval guidance",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:95",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:106] avoids repeating allowFrom guidance in the no-route fallback",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:106",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:119] explains how to enable Matrix native approvals when Matrix is the initiating platform",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:119",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:216] normalizes reply metadata and filters invalid decisions",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:216",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:239] builds pending reply payloads with trimmed warning text and slug fallback",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:239",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:306] compacts structured cwd paths in pending reply payloads",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:306",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:319] omits allow-always actions when the effective policy requires approval every time",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:319",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:371] stores agent and session metadata for downstream suppression checks",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:371",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:393] uses a longer fence for commands containing triple backticks",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:393",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:407] clamps pending reply expiration to zero seconds",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:407",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:420] formats longer approval windows in minutes",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:420",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:433] builds shared exec approval action descriptors and interactive replies",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:433",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:492] builds and parses shared exec approval command text",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:492",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/exec-approval-reply.test.ts:523] builds unavailable payloads for approver DMs",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/exec-approval-reply.test.ts:523",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
