// v2026.7.1 OpenClaw parity mirror of src/infra/tailscale.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:53] parses DNS name from tailscale status",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:53",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:63] falls back to IP when DNS missing",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:63",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:71] parses noisy JSON output from tailscale status",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:71",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:80] parses noisy JSON output from tailscale whois",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:80",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:92] caches malformed tailscale whois output on the short error TTL path",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:92",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:121] does not cache whois results when the cache expiry would exceed Date range",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:121",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:143] allows the test binary override in explicit test environments",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:143",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:151] ignores the test binary override outside test environments",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:151",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:159] enableTailscaleServe attempts normal first, then sudo",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:159",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:178] enableTailscaleServe does NOT use sudo if first attempt succeeds",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:178",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:190] enableTailscaleServe passes a configured service name",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:190",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:208] disableTailscaleServe uses fallback",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:208",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:223] disableTailscaleServe disables only the configured service name",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:223",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:235] enableTailscaleServe skips sudo on non-permission errors",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:235",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:243] enableTailscaleServe rethrows original error if sudo fails",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:243",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:257] hasTailscaleFunnelRouteForPort accepts noisy JSON status output",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:257",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:266] hasTailscaleFunnelRouteForPort preserves malformed status parse failures",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:266",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:286] matches a Funnel route whose Proxy is a full http URL",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:286",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:291] matches a Proxy URL with a trailing slash",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:291",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:296] matches a Proxy URL with a longer path",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:296",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:301] matches the localhost loopback alias",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:301",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:306] matches an IPv6 loopback Proxy",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:306",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:311] matches the documented https+insecure target scheme",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:311",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:318] matches https+insecure with a trailing path",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:318",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:325] does not match https+insecure on a non-loopback host",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:325",
               "upstream it() block #24",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:332] matches a bare port form",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:332",
               "upstream it() block #25",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:337] does not match a Proxy on a different port",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:337",
               "upstream it() block #26",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:342] does not match a non-loopback host on the right port",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:342",
               "upstream it() block #27",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:347] ignores Web entries whose host is not in AllowFunnel",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:347",
               "upstream it() block #28",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/infra/tailscale.test.ts:359] returns false on an empty status payload",
          "[v7_1][parity_gap][infra]") {
    PARITY_GAP("src/infra/tailscale.test.ts:359",
               "upstream it() block #29",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
