// v2026.7.1 OpenClaw parity mirror of extensions/browser/src/browser/chrome.internal.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../../parity.hpp"

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:316] falls back to the default profile name when none is supplied",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:316",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:321] respects an explicit profile name",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:321",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:349] toggles headless args",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:349",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:359] lets profile headless=false override global headless=true",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:359",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:369] lets a request headless override beat env and profile headed settings",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:369",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:381] adds headless args for Linux local managed profiles without a display",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:381",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:393] does not apply Linux no-display fallback to remote profiles",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:393",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:410] toggles no-sandbox args",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:410",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:420] adds --disable-dev-shm-usage on linux",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:420",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:431] uses a non-interactive keychain for isolated managed profiles on macOS",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:431",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:443] keeps existing macOS profiles on their original keychain",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:443",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:453] propagates extraArgs",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:453",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:466] launches managed Chrome direct by default",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:466",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:477] treats a throwing fs.existsSync (for prefs files) as non-existent to force bootstrap",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:477",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:561] rejects a remote profile before attempting to spawn",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:561",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:575] throws when no supported browser executable is found",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:575",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:610] completes successfully when Chrome reports /json/version and CDP is reachable",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:610",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:662] accepts a ready CDP diagnostic after the launch HTTP probe expires",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:662",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:715] keeps the launched process when fallback diagnostic sees HTTP before WS readiness",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:715",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:775] uses profile executablePath over global executablePath when launching",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:775",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:807] clears stale singleton locks and retries once after profile-in-use launch failure",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:807",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:885] stops a lock-owned stale managed CDP listener before relaunching",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:885",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:976] does not stop a current-host lock pid without managed Chrome ownership proof",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:976",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1059] does not stop a stale CDP listener without current-host profile ownership proof",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1059",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1081] throws with stderr hint + sandbox hint when CDP never becomes reachable",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1081",
               "upstream it() block #24",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1125] uses the configured local launch timeout while waiting for CDP discovery",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1125",
               "upstream it() block #25",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1156] escalates to SIGKILL when CDP keeps reporting reachable past the deadline",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1156",
               "upstream it() block #26",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1177] returns null when the /json/version response JSON is not an object",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1177",
               "upstream it() block #27",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1192] returns null when /json/version omits webSocketDebuggerUrl",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1192",
               "upstream it() block #28",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1205] returns false when getChromeWebSocketUrl resolves to null",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1205",
               "upstream it() block #29",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1218] returns false when the ws upgrade is refused",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1218",
               "upstream it() block #30",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1235] returns false when the health command response is malformed JSON",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1235",
               "upstream it() block #31",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1252] ignores messages whose id does not match the health probe id",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1252",
               "upstream it() block #32",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1269] returns true when Browser.getVersion responds with an object",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1269",
               "upstream it() block #33",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1291] resolves false when the direct-ws probe cannot connect",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1291",
               "upstream it() block #34",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1310] resolves true when the direct-ws handshake succeeds",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1310",
               "upstream it() block #35",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1336] returns the input URL as-is for handshake-ready direct ws endpoints",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1336",
               "upstream it() block #36",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1347] resolves false when the ws client cannot connect to the discovered ws URL",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1347",
               "upstream it() block #37",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1390] resolves false when the ws ",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1390",
               "upstream it() block #38",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1407] returns false when getChromeWebSocketUrl rejects (SSRF-blocked)",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1407",
               "upstream it() block #39",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1427] skips decoration entirely when the profile is already decorated",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1427",
               "upstream it() block #40",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1500] falls back to the default color when profile.color is undefined",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1500",
               "upstream it() block #41",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1540] buffers stderr chunks when Chrome emits diagnostics while CDP comes up",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1540",
               "upstream it() block #42",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1596] omits the sandbox hint on non-linux platforms",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1596",
               "upstream it() block #43",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1643] breaks out of the bootstrap prefs-wait loop as soon as both files exist",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1643",
               "upstream it() block #44",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1694] breaks out of the bootstrap exit-wait loop once the child reports an exit code",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1694",
               "upstream it() block #45",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1748] logs a warning when decorateOpenClawProfile throws and still returns a running Chrome",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1748",
               "upstream it() block #46",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1804] logs pid as -1 when the spawned proc reports no pid",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1804",
               "upstream it() block #47",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1884] preflights managed-proxy policy and registers exact CDP probe URLs",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1884",
               "upstream it() block #48",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1907] releases scoped bypass registrations when the CDP probe never succeeds",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1907",
               "upstream it() block #49",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1929] surfaces loopbackMode=block as BrowserProfileUnavailableError without spawning Chrome",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1929",
               "upstream it() block #50",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/browser/src/browser/chrome.internal.test.ts:1946] does not register a bypass for a remote attachOnly CDP URL (loopback gate)",
          "[v7_1][parity_gap][browser]") {
    PARITY_GAP("extensions/browser/src/browser/chrome.internal.test.ts:1946",
               "upstream it() block #51",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
