// v2026.7.1 OpenClaw parity mirror of extensions/codex/src/conversation-control.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [extensions/codex/src/conversation-control.test.ts:84] persists fast mode and permissions for later bound turns",
          "[v7_1][parity_gap][codex]") {
    PARITY_GAP("extensions/codex/src/conversation-control.test.ts:84",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/codex/src/conversation-control.test.ts:109] does not persist public OpenAI provider after model changes on native auth bindings",
          "[v7_1][parity_gap][codex]") {
    PARITY_GAP("extensions/codex/src/conversation-control.test.ts:109",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/codex/src/conversation-control.test.ts:150] keeps Guardian reviewer when switching a stale local binding to a provider-qualified OpenAI model",
          "[v7_1][parity_gap][codex]") {
    PARITY_GAP("extensions/codex/src/conversation-control.test.ts:150",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/codex/src/conversation-control.test.ts:183] keeps the bound local provider when switching to another unqualified model",
          "[v7_1][parity_gap][codex]") {
    PARITY_GAP("extensions/codex/src/conversation-control.test.ts:183",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/codex/src/conversation-control.test.ts:214] keeps the bound local provider when reselecting a model id with a slash",
          "[v7_1][parity_gap][codex]") {
    PARITY_GAP("extensions/codex/src/conversation-control.test.ts:214",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/codex/src/conversation-control.test.ts:247] escapes model names returned from Codex before chat display",
          "[v7_1][parity_gap][codex]") {
    PARITY_GAP("extensions/codex/src/conversation-control.test.ts:247",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
