// v2026.7.1 OpenClaw parity mirror of extensions/slack/src/message-tools.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:28] classifies provider-native mutation actions",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:28",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:38] describes configured Slack message actions without loading channel runtime",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:38",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:69] honors account-scoped action gates",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:69",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:92] includes file actions when message actions are enabled",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:92",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:121] honors the selected Slack account during discovery",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:121",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:172] describes Slack file ids separately from message ids",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:172",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:192] describes current Slack message id actions without stale aliases",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:192",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:214] describes Slack shortcode and common glyph reaction inputs",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:214",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:232] omits the react emoji schema when reactions are disabled",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:232",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:255] describes Slack reply broadcasts as send-only thread hints",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:255",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:274] describes Slack top-level sends as a same-channel thread opt-out",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:274",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/slack/src/message-tools.test.ts:293] omits Slack file and message id schemas when those actions are disabled",
          "[v7_1][parity_gap][slack]") {
    PARITY_GAP("extensions/slack/src/message-tools.test.ts:293",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
