// v2026.7.1 OpenClaw parity mirror of src/agents/auth-profiles/session-override.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:168] returns early when no auth sources exist",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:168",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:202] keeps user override when provider alias differs",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:202",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:233] keeps config-only aws-sdk user overrides",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:233",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:283] clears aws-sdk config override when stored profile drifted to another provider",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:283",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:342] keeps explicit user override when stored order prefers another profile",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:342",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:390] keeps session override when CLI provider aliases the stored profile provider",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:390",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:432] keeps a session override from an accepted runtime auth provider",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:432",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:475] keeps user-pinned normal OpenAI API-key profiles for Codex sessions",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:475",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:524] re-resolves a stale user session override when the selected profile becomes unusable",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:524",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:575] clears auth state without restoring concurrent session management fields",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:575",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/agents/auth-profiles/session-override.test.ts:609] rotates auth state without restoring concurrent session management fields",
          "[v7_1][parity_gap][agents]") {
    PARITY_GAP("src/agents/auth-profiles/session-override.test.ts:609",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
