// v2026.5.2 OpenClaw parity mirror of src/agents/tools/media-tool-shared.test.ts
//
// Auto-generated by tests/v5_2/generate.py from the openclaw v2026.5.2
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:35] does not widen default local roots from media sources",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:35",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:60] normalizes provider and model refs before registry lookup",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:60",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:74] reports the normalized ref when the registry lookup misses",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:74",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:86] falls back to provider-prefixed custom model IDs",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:86",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:107] allows generation tools for runtime providers configured without auth",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:107",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:122] omits generation tools when runtime providers are not configured",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:122",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:137] keeps explicit model config sufficient for generation tool registration",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:137",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/agents/tools/media-tool-shared.test.ts:150] checks configured runtime providers against the supplied auth store",
          "[v5_2][parity_gap][agents]") {
    PARITY_GAP("src/agents/tools/media-tool-shared.test.ts:150",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
