// v2026.5.2 OpenClaw parity mirror of ui/src/ui/realtime-talk.test.ts
//
// Auto-generated by tests/v5_2/generate.py from the openclaw v2026.5.2
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v5.2 [ui/src/ui/realtime-talk.test.ts:59] starts the Google Live WebSocket transport from a generic session result",
          "[v5_2][parity_gap]") {
    PARITY_GAP("ui/src/ui/realtime-talk.test.ts:59",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [ui/src/ui/realtime-talk.test.ts:86] keeps Google Live WebSocket sessions off the WebRTC fallback when transport is omitted",
          "[v5_2][parity_gap]") {
    PARITY_GAP("ui/src/ui/realtime-talk.test.ts:86",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [ui/src/ui/realtime-talk.test.ts:108] does not treat ambiguous Google sessions as browser WebRTC sessions",
          "[v5_2][parity_gap]") {
    PARITY_GAP("ui/src/ui/realtime-talk.test.ts:108",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [ui/src/ui/realtime-talk.test.ts:123] does not infer Google Live transport from websocketUrl on non-Google sessions",
          "[v5_2][parity_gap]") {
    PARITY_GAP("ui/src/ui/realtime-talk.test.ts:123",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [ui/src/ui/realtime-talk.test.ts:137] starts the Gateway relay transport for backend-only realtime providers",
          "[v5_2][parity_gap]") {
    PARITY_GAP("ui/src/ui/realtime-talk.test.ts:137",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [ui/src/ui/realtime-talk.test.ts:161] keeps legacy session results on the OpenAI-style WebRTC transport",
          "[v5_2][parity_gap]") {
    PARITY_GAP("ui/src/ui/realtime-talk.test.ts:161",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
