// v2026.7.1 OpenClaw parity mirror of extensions/arcee/index.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [extensions/arcee/index.test.ts:12] registers Arcee AI with direct and OpenRouter auth choices",
          "[v7_1][parity_gap][arcee]") {
    PARITY_GAP("extensions/arcee/index.test.ts:12",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/arcee/index.test.ts:41] stores the OpenRouter onboarding path under the OpenRouter auth profile",
          "[v7_1][parity_gap][arcee]") {
    PARITY_GAP("extensions/arcee/index.test.ts:41",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/arcee/index.test.ts:77] keeps direct Arcee auth env candidates separate from OpenRouter",
          "[v7_1][parity_gap][arcee]") {
    PARITY_GAP("extensions/arcee/index.test.ts:77",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/arcee/index.test.ts:84] builds the direct Arcee AI model catalog",
          "[v7_1][parity_gap][arcee]") {
    PARITY_GAP("extensions/arcee/index.test.ts:84",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/arcee/index.test.ts:105] builds the OpenRouter-backed Arcee AI model catalog",
          "[v7_1][parity_gap][arcee]") {
    PARITY_GAP("extensions/arcee/index.test.ts:105",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/arcee/index.test.ts:130] normalizes Arcee OpenRouter models to vendor-prefixed runtime ids",
          "[v7_1][parity_gap][arcee]") {
    PARITY_GAP("extensions/arcee/index.test.ts:130",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/arcee/index.test.ts:159] canonicalizes stale OpenRouter /v1 config and transport metadata",
          "[v7_1][parity_gap][arcee]") {
    PARITY_GAP("extensions/arcee/index.test.ts:159",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
