// v2026.7.1 OpenClaw parity mirror of src/commands/status.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/commands/status.test.ts:1013] prints JSON and includes security audit only when all is requested",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1013",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1057] scopes usage resolution to the scanned config",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1057",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1088] keeps default text status off the security audit path",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1088",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1094] passes deep mode through to the text status scan",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1094",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1106] surfaces unknown usage when totalTokens is missing",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1106",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1118] surfaces stale usage when totalTokens is preserved but not fresh",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1118",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1137] prints formatted lines with verbose cache details",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1137",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1174] shows a maintenance hint when task audit errors are present",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1174",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1234] uses prompt-side denominator for cached percentages",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1234",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1261] shows node-only gateway info when no local gateway service is installed",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1261",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1288] shows gateway auth when reachable",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1288",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1307] warns instead of crashing when gateway auth SecretRef is unresolved for probe auth",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1307",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1337] notes when secret diagnostics may come from a CLI process outside the service wrapper context",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1337",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1378] surfaces channel runtime errors from the gateway",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1378",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1421] prints safe gateway pairing recovery guidance",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1421",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/commands/status.test.ts:1500] includes sessions across agents in JSON output",
          "[v7_1][parity_gap][commands]") {
    PARITY_GAP("src/commands/status.test.ts:1500",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
