// v2026.4.29 OpenClaw parity mirror of src/cron/isolated-agent/subagent-followup.test.ts
//
// Auto-generated by tests/v4_29/generate.py from the openclaw v2026.4.29
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HAND_AUTHORED sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] detects ",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:66",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] detects subagent-related interim text",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:69",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] rejects substantive content",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:74",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] does not treat empty as interim (empty = NO_REPLY was stripped)",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:79",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] does not treat whitespace-only as interim",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:83",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns true for subagent spawn hints",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:89",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns false for plain interim text",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:95",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns false for empty string",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:99",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns undefined when no descendants exist",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:107",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] reads reply from child session transcript",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:116",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] falls back to frozenResultText when session transcript unavailable",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:126",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] prefers session transcript over frozenResultText",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:141",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] joins replies from multiple descendants",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:153",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] skips SILENT_REPLY_TOKEN descendants",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:172",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns undefined when frozenResultText is null",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:196",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] ignores descendants that ended before run started",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:211",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns initialReply immediately when no active descendants and observedActiveDescendants=false",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:251",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] awaits active descendants via agent.wait and returns synthesis after grace period",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:263",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns undefined when descendants finish but only interim text remains after grace period",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:300",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] returns synthesis even if initial reply was undefined",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:319",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] uses agent.wait for each active run when multiple descendants exist",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:347",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] waits for newly discovered active descendants after the first wait round",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:391",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] handles agent.wait errors gracefully and still reads the synthesis",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:435",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cron/isolated-agent/subagent-followup.test.ts] skips NO_REPLY synthesis and returns undefined",
          "[v4_29][parity_gap][cron]") {
    PARITY_GAP("src/cron/isolated-agent/subagent-followup.test.ts:463",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
