// v2026.4.29 OpenClaw parity mirror of extensions/telegram/src/reply-parameters.test.ts
//
// Auto-generated by tests/v4_29/generate.py from the openclaw v2026.4.29
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v4.29 [extensions/telegram/src/reply-parameters.test.ts:10] preserves exact quote text and quote metadata for native Telegram replies",
          "[v4_29][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/reply-parameters.test.ts:10",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [extensions/telegram/src/reply-parameters.test.ts:34] uses the selected reply id as the quote id when direct sends only provide quote text",
          "[v4_29][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/reply-parameters.test.ts:34",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [extensions/telegram/src/reply-parameters.test.ts:50] falls back to legacy reply id for blank quotes or mismatched quote sources",
          "[v4_29][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/reply-parameters.test.ts:50",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [extensions/telegram/src/reply-parameters.test.ts:73] converts rejected native quote params to legacy reply params for retry",
          "[v4_29][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/reply-parameters.test.ts:73",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [extensions/telegram/src/reply-parameters.test.ts:90] keeps direct-message topic scope for Telegram DM topics",
          "[v4_29][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/reply-parameters.test.ts:90",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
