// v2026.7.1 OpenClaw parity mirror of extensions/telegram/src/auto-topic-label.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [extensions/telegram/src/auto-topic-label.test.ts:17] returns enabled with default prompt when configs are undefined",
          "[v7_1][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/auto-topic-label.test.ts:17",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/telegram/src/auto-topic-label.test.ts:22] prefers direct config over account config",
          "[v7_1][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/auto-topic-label.test.ts:22",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/telegram/src/auto-topic-label.test.ts:32] falls back to default prompt for empty object prompt",
          "[v7_1][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/auto-topic-label.test.ts:32",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/telegram/src/auto-topic-label.test.ts:41] delegates to the generic conversation label helper with telegram max length",
          "[v7_1][parity_gap][telegram]") {
    PARITY_GAP("extensions/telegram/src/auto-topic-label.test.ts:41",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
