// v2026.7.1 OpenClaw parity mirror of src/channels/mention-gating.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:11] combines explicit, implicit, and bypass mentions",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:11",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:23] skips when mention required and none detected",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:23",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:67] allows matching implicit mention kinds by default",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:67",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:88] filters implicit mention kinds through the allowlist",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:88",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:109] blocks implicit mention kinds excluded by policy",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:109",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:131] dedupes repeated implicit mention kinds",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:131",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:149] keeps command bypass behavior unchanged",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:149",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:170] does not allow command bypass when some other mention is present",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:170",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:191] does not allow command bypass outside groups",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:191",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:212] keeps the flat call shape for compatibility",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:212",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:262] returns a one-item list when enabled",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:262",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/mention-gating.test.ts:266] returns an empty list when disabled",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/mention-gating.test.ts:266",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
