// v2026.7.1 OpenClaw parity mirror of src/channels/registry.helpers.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/channels/registry.helpers.test.ts:50] keeps Feishu first in the current default order",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/registry.helpers.test.ts:50",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/registry.helpers.test.ts:55] includes MS Teams in the bundled channel list",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/registry.helpers.test.ts:55",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/registry.helpers.test.ts:59] formats Telegram selection lines without a docs prefix and with website extras",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/registry.helpers.test.ts:59",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/registry.helpers.test.ts:70] prefers the pinned channel registry when resolving registered plugin channels",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/registry.helpers.test.ts:70",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/registry.helpers.test.ts:83] falls back to the active registry when the pinned channel registry has no channels",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/registry.helpers.test.ts:83",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/registry.helpers.test.ts:95] rebuilds registered channel lookups when pinned-empty fallback active registry changes",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/registry.helpers.test.ts:95",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/channels/registry.helpers.test.ts:117] refreshes registered channel lookups when selected registry channels grow in place",
          "[v7_1][parity_gap][channels]") {
    PARITY_GAP("src/channels/registry.helpers.test.ts:117",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
