// v2026.7.1 OpenClaw parity mirror of src/auto-reply/reply/commands-steer.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:47] queues steering for the active current text-command session",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:47",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:69] prefers the native command target session key over the slash-command session",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:69",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:92] falls back to the stored session id when it is still active",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:92",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:114] resolves an active run from the target session file before stored session id fallback",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:114",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:152] falls back from a slash-lane command session to an active direct sibling",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:152",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:180] returns usage for an empty steer command",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:180",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:190] continues as a normal prompt when no current session run is active",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:190",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:204] continues as a normal prompt when the active run rejects steering injection",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:204",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:229] continues as a normal prompt when steering throws",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:229",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/commands-steer.test.ts:245] continues as a normal prompt when the active run is compacting",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/commands-steer.test.ts:245",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
