// v2026.7.1 OpenClaw parity mirror of src/auto-reply/reply/session-reset-model.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [src/auto-reply/reply/session-reset-model.test.ts:63] selects a model hint and strips it from the body",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/session-reset-model.test.ts:63",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/session-reset-model.test.ts:73] clears auth profile overrides when reset applies a model",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/session-reset-model.test.ts:73",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/session-reset-model.test.ts:88] adopts a concurrent model winner instead of acknowledging the reset hint",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/session-reset-model.test.ts:88",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/session-reset-model.test.ts:140] checks the persisted winner for an explicit same-value reset hint",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/session-reset-model.test.ts:140",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/session-reset-model.test.ts:189] rejects a reset-model hint when the session rotates during persistence",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/session-reset-model.test.ts:189",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/auto-reply/reply/session-reset-model.test.ts:237] skips when resetTriggered is false",
          "[v7_1][parity_gap][auto-reply]") {
    PARITY_GAP("src/auto-reply/reply/session-reset-model.test.ts:237",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
