// v2026.5.2 OpenClaw parity mirror of src/tasks/task-executor-policy.test.ts
//
// Auto-generated by tests/v5_2/generate.py from the openclaw v2026.5.2
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v5.2 [src/tasks/task-executor-policy.test.ts:30] identifies terminal statuses",
          "[v5_2][parity_gap][tasks]") {
    PARITY_GAP("src/tasks/task-executor-policy.test.ts:30",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/tasks/task-executor-policy.test.ts:40] formats terminal, followup, and progress messages",
          "[v5_2][parity_gap][tasks]") {
    PARITY_GAP("src/tasks/task-executor-policy.test.ts:40",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/tasks/task-executor-policy.test.ts:65] sanitizes leaked internal runtime context from terminal and progress copy",
          "[v5_2][parity_gap][tasks]") {
    PARITY_GAP("src/tasks/task-executor-policy.test.ts:65",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/tasks/task-executor-policy.test.ts:105] redacts raw exec denial text from blocked task updates",
          "[v5_2][parity_gap][tasks]") {
    PARITY_GAP("src/tasks/task-executor-policy.test.ts:105",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/tasks/task-executor-policy.test.ts:122] keeps delivery policy decisions explicit",
          "[v5_2][parity_gap][tasks]") {
    PARITY_GAP("src/tasks/task-executor-policy.test.ts:122",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
