// v2026.7.1 OpenClaw parity mirror of extensions/matrix/src/matrix/accounts.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../../parity.hpp"

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:178] treats access-token-only config as configured",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:178",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:192] treats SecretRef access-token config as configured",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:192",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:214] treats accounts.default SecretRef access-token config as configured",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:214",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:240] treats accounts.default SecretRef password config as configured",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:240",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:267] requires userId + password when no access token is set",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:267",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:281] marks password auth as configured when userId is present",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:281",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:296] merges account bot loop protection over top-level defaults field-by-field",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:296",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:328] normalizes and de-duplicates configured account ids",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:328",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:355] returns the only named account when no explicit default is set",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:355",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:372] uses configured defaultAccount when accountId is omitted",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:372",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:395] includes env-backed named accounts in plugin account enumeration",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:395",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:410] includes default accounts backed only by global env vars in plugin account enumeration",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:410",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:420] treats mixed default and named env-backed accounts as multi-account",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:420",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:437] includes a top-level configured default account alongside named accounts",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:437",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:457] does not materialize a default account from shared top-level defaults alone",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:457",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:477] uses the synthetic ",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:477",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:498] collects other configured Matrix account user ids for bot detection",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:498",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:526] honors injected env when detecting configured bot accounts",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:526",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:547] falls back to stored credentials when an access-token-only account omits userId",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:547",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:581] preserves shared nested dm and actions config when an account overrides one field",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:581",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:624] filters channel-level groups by room account in multi-account setups",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:624",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:628] filters channel-level groups when the default account is configured at the top level",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:628",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:635] filters legacy channel-level rooms by room account in multi-account setups",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:635",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:639] filters legacy channel-level rooms when the default account is configured at the top level",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:639",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:646] honors injected env when scoping room entries in multi-account setups",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:646",
               "upstream it() block #24",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:685] keeps scoped groups bound to their account even when only one account is active",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:685",
               "upstream it() block #25",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:715] keeps scoped legacy rooms bound to their account even when only one account is active",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:715",
               "upstream it() block #26",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:745] lets an account clear inherited groups with an explicit empty map",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:745",
               "upstream it() block #27",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/matrix/src/matrix/accounts.test.ts:768] lets an account clear inherited legacy rooms with an explicit empty map",
          "[v7_1][parity_gap][matrix]") {
    PARITY_GAP("extensions/matrix/src/matrix/accounts.test.ts:768",
               "upstream it() block #28",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
