// v2026.7.1 OpenClaw parity mirror of src/skills/workshop/tool-policy-diagnostic.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:10] names the profile and exact additive grant when policy excludes the tool",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:10",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:18] returns no diagnostic when policy includes the tool",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:18",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:23] returns no diagnostic when Workshop capture is disabled",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:23",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:27] names a restrictive allowlist that excludes the tool",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:27",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:35] names agent-scoped profile and allowlist sources",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:35",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:55] targets the effective agent-scoped profile grant owner",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:55",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:67] names the matching provider profile source",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:67",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:79] targets the effective agent-scoped provider profile grant owner",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:79",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:99] names the matching agent provider allowlist source",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:99",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/skills/workshop/tool-policy-diagnostic.test.ts:118] names an explicit deny and its removal",
          "[v7_1][parity_gap][skills]") {
    PARITY_GAP("src/skills/workshop/tool-policy-diagnostic.test.ts:118",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
