// v2026.7.1 OpenClaw parity mirror of src/gateway/client.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/gateway/client.test.ts:314] blocks ws:// to non-loopback addresses (CWE-319)",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:314",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:328] handles malformed URLs gracefully without crashing",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:328",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:342] allows ws:// to loopback addresses",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:342",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:357] does not treat hostnames starting with 127 as loopback",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:357",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:371] allows ws:// to IPv4-mapped loopback addresses",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:371",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:385] bootstraps inherited managed proxy routing before proxy-mode loopback WebSocket creation",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:385",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:411] keeps gateway-only loopback bypass active only during WebSocket construction",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:411",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:442] clears gateway-only loopback bypass when WebSocket connection errors before opening",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:442",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:467] proxies ws:// loopback addresses when active proxy loopbackMode is proxy",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:467",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:492] blocks ws:// loopback addresses when active proxy loopbackMode is block",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:492",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:514] allows wss:// to any address",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:514",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:528] allows ws:// to private addresses for trusted LAN and Tailnet configs",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:528",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:542] allows ws:// to IPv6 link-local addresses across fe80::/10",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:542",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:556] allows ws:// hostnames with OPENCLAW_ALLOW_INSECURE_PRIVATE_WS=1",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:556",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:573] preserves retry metadata from gateway error responses",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:573",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:630] retries startup-unavailable connect failures without terminal callbacks",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:630",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:706] clears stale token on device token mismatch close",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:706",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:736] does not break close flow when token clear throws",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:736",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:758] does not clear auth state for non-mismatch close reasons",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:758",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:775] marks an opened TLS transport unvalidated when fingerprint verification fails",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:775",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:802] keeps close callback errors inside websocket dispatch",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:802",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:823] keeps a managed reconnect timer after gateway restart closes",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:823",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:846] reconnects quietly after one clean pre-hello close with a pending connect",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:846",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:921] surfaces repeated clean pre-hello closes with a pending connect",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:921",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:988] clears pending reconnect timers on stop",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:988",
               "upstream it() block #24",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1007] force-terminates a lingering socket after stop",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1007",
               "upstream it() block #25",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1031] does not force-terminate a socket that closes during stop",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1031",
               "upstream it() block #26",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1052] waits for a lingering socket to terminate in stopAndWait",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1052",
               "upstream it() block #27",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1085] does not clear persisted device auth when explicit shared token is provided",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1085",
               "upstream it() block #28",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1119] keeps event callback errors inside message dispatch",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1119",
               "upstream it() block #29",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1202] advertises the default protocol compatibility range",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1202",
               "upstream it() block #30",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1244] surfaces connect assembly errors instead of waiting for the wrapper timeout",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1244",
               "upstream it() block #31",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1285] keeps connect error callback throws inside challenge dispatch",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1285",
               "upstream it() block #32",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1314] keeps hello callback errors inside connect dispatch",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1314",
               "upstream it() block #33",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1419] uses explicit shared token and does not inject stored device token",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1419",
               "upstream it() block #34",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1438] retries without approval runtime token when a gateway rejects the auth field",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1438",
               "upstream it() block #35",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1474] fails closed when a gateway rejects the required agent runtime identity auth field",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1474",
               "upstream it() block #36",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1512] waits for socket open before sending connect after an early challenge",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1512",
               "upstream it() block #37",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1527] logs stopped connect handshakes at debug level during teardown",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1527",
               "upstream it() block #38",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1552] redacts secret-bearing connect failure logs",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1552",
               "upstream it() block #39",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1578] preserves trailing diagnostics after redacted connect failure URL query params",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1578",
               "upstream it() block #40",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1603] forces secret redaction for connect failure logs when general log redaction is off",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1603",
               "upstream it() block #41",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1628] uses explicit shared password and does not inject stored device token",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1628",
               "upstream it() block #42",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1648] prefers explicit shared password over bootstrap token",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1648",
               "upstream it() block #43",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1668] uses stored device token scopes when shared token is not provided",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1668",
               "upstream it() block #44",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1690] keeps requested scopes when reusing a stored device token",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1690",
               "upstream it() block #45",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1713] loads stored device auth from the provided env",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1713",
               "upstream it() block #46",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1748] uses bootstrap token when no shared or device token is available",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1748",
               "upstream it() block #47",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1768] prefers explicit deviceToken over stored device token",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1768",
               "upstream it() block #48",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1792] falls back to requested scopes when stored device token has no cached scopes",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1792",
               "upstream it() block #49",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1815] retries with stored device token after shared-token mismatch on trusted endpoints",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1815",
               "upstream it() block #50",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1843] retries with stored device token when server recommends retry_with_device_token",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1843",
               "upstream it() block #51",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1863] does not auto-reconnect on AUTH_TOKEN_MISSING connect failures",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1863",
               "upstream it() block #52",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1885] keeps reconnect paused callback errors inside close dispatch",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1885",
               "upstream it() block #53",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1921] does not auto-reconnect on CLIENT_VERSION_MISMATCH connect failures",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1921",
               "upstream it() block #54",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1949] does not auto-reconnect on token mismatch when no device-token retry is available",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1949",
               "upstream it() block #55",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:1972] keeps reconnecting on PAIRING_REQUIRED when retry hints keep reconnect active",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:1972",
               "upstream it() block #56",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:2003] clears stale stored device tokens and does not reconnect on AUTH_DEVICE_TOKEN_MISMATCH",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:2003",
               "upstream it() block #57",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:2035] clears stale stored device tokens from the configured environment store",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:2035",
               "upstream it() block #58",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:2067] does not clear stored device tokens or reconnect on AUTH_SCOPE_MISMATCH",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:2067",
               "upstream it() block #59",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/client.test.ts:2094] does not auto-reconnect on token mismatch when retry is not trusted",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/client.test.ts:2094",
               "upstream it() block #60",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
