// v2026.7.1 OpenClaw parity mirror of src/gateway/server-chat.stream-text-merge.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/gateway/server-chat.stream-text-merge.test.ts:43] keeps cumulative snapshots from duplicating already-buffered text",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/server-chat.stream-text-merge.test.ts:43",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/server-chat.stream-text-merge.test.ts:53] keeps non-prefix incremental segments after tool calls",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/server-chat.stream-text-merge.test.ts:53",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/server-chat.stream-text-merge.test.ts:63] replaces prior live text when Codex assistant item switches with empty delta",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/server-chat.stream-text-merge.test.ts:63",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/server-chat.stream-text-merge.test.ts:75] would concatenate superseded text if replacement incorrectly included delta",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/server-chat.stream-text-merge.test.ts:75",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/gateway/server-chat.stream-text-merge.test.ts:86] caps merged live text while preserving the newest assistant output",
          "[v7_1][parity_gap][gateway]") {
    PARITY_GAP("src/gateway/server-chat.stream-text-merge.test.ts:86",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
