// v2026.4.29 OpenClaw parity mirror of src/config/talk.normalize.test.ts
//
// Auto-generated by tests/v4_29/generate.py from the openclaw v2026.4.29
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HAND_AUTHORED sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v4.29 [src/config/talk.normalize.test.ts] keeps core Talk normalization generic and ignores legacy provider-flat fields",
          "[v4_29][parity_gap][config]") {
    PARITY_GAP("src/config/talk.normalize.test.ts:6",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/config/talk.normalize.test.ts] uses new provider/providers shape directly when present",
          "[v4_29][parity_gap][config]") {
    PARITY_GAP("src/config/talk.normalize.test.ts:25",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/config/talk.normalize.test.ts] merges duplicate provider ids after trimming",
          "[v4_29][parity_gap][config]") {
    PARITY_GAP("src/config/talk.normalize.test.ts:49",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/config/talk.normalize.test.ts] builds a canonical resolved talk payload for clients",
          "[v4_29][parity_gap][config]") {
    PARITY_GAP("src/config/talk.normalize.test.ts:73",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/config/talk.normalize.test.ts] preserves SecretRef apiKey values during normalization",
          "[v4_29][parity_gap][config]") {
    PARITY_GAP("src/config/talk.normalize.test.ts:106",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/config/talk.normalize.test.ts] does not inject provider apiKey defaults during snapshot materialization",
          "[v4_29][parity_gap][config]") {
    PARITY_GAP("src/config/talk.normalize.test.ts:126",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
