// v2026.7.1 OpenClaw parity mirror of extensions/file-transfer/src/shared/errors.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../../parity.hpp"

TEST_CASE("v7.1 [extensions/file-transfer/src/shared/errors.test.ts:6] returns an error envelope without canonicalPath when omitted",
          "[v7_1][parity_gap][file-transfer]") {
    PARITY_GAP("extensions/file-transfer/src/shared/errors.test.ts:6",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/file-transfer/src/shared/errors.test.ts:12] includes canonicalPath only when provided non-empty",
          "[v7_1][parity_gap][file-transfer]") {
    PARITY_GAP("extensions/file-transfer/src/shared/errors.test.ts:12",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/file-transfer/src/shared/errors.test.ts:22] preserves code and message in the thrown Error",
          "[v7_1][parity_gap][file-transfer]") {
    PARITY_GAP("extensions/file-transfer/src/shared/errors.test.ts:22",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/file-transfer/src/shared/errors.test.ts:28] appends canonicalPath when present",
          "[v7_1][parity_gap][file-transfer]") {
    PARITY_GAP("extensions/file-transfer/src/shared/errors.test.ts:28",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [extensions/file-transfer/src/shared/errors.test.ts:38] falls back to ERROR / generic message when fields are missing",
          "[v7_1][parity_gap][file-transfer]") {
    PARITY_GAP("extensions/file-transfer/src/shared/errors.test.ts:38",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
