// v2026.5.2 OpenClaw parity mirror of extensions/ollama/src/web-search-provider.test.ts
//
// Auto-generated by tests/v5_2/generate.py from the openclaw v2026.5.2
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:77] registers a keyless web search provider",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:77",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:86] uses the configured Ollama host and enables the plugin in config",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:86",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:111] prefers the plugin web search base URL over the model provider host",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:111",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:119] uses the configured Ollama Cloud host for web search",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:119",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:129] uses the model provider baseURL alias for web search",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:129",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:140] maps generic search args into the local Ollama proxy endpoint",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:140",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:199] tries the future local direct endpoint when the local proxy endpoint is missing",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:199",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:231] uses only the hosted endpoint for Ollama Cloud base URLs",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:231",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:262] uses an env Ollama key only for the cloud fallback from a local host",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:262",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:319] surfaces Ollama signin guidance for 401 responses",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:319",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:330] warns when Ollama is not reachable during setup without cancelling",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:330",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:350] resolves env var when config apiKey is a marker string",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:350",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [extensions/ollama/src/web-search-provider.test.ts:370] warns when ollama signin is missing during setup without cancelling",
          "[v5_2][parity_gap][ollama]") {
    PARITY_GAP("extensions/ollama/src/web-search-provider.test.ts:370",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
