// v2026.7.1 OpenClaw parity mirror of src/media/web-media.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/media/web-media.test.ts:330] loads browser-style canvas media paths as managed local files",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:330",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:340] keeps trying hosted media resolvers after one throws",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:340",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:370] surfaces Rastermill decode failures when image optimization cannot produce a JPEG",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:370",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:376] uses model metadata-aware image compression grids",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:376",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:430] adapts automatic image compression for many-image turns",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:430",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:448] preserves in-limit GIF buffers when optimizing direct image buffers",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:448",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:463] does not bypass model dimensions for GIF buffers",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:463",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:475] applies model image maxBytes to the effective image cap",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:475",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:487] uses the strictest model image maxBytes across fallback candidates",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:487",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:496] downscales oversized JPEGs to the resolved model side limit before returning media",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:496",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:523] downscales alpha PNGs to the resolved model side limit before returning media",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:523",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:544] uses low default dimensions when model metadata is unavailable",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:544",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:553] resolves relative local media paths against the provided workspace directory",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:553",
               "upstream it() block #12",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:563] does not treat image-named generic container bytes as local image media",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:563",
               "upstream it() block #13",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:576] strips internal media-store UUID suffix from outbound fileName",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:576",
               "upstream it() block #14",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:591] preserves non-media-store filenames that match the UUID suffix shape",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:591",
               "upstream it() block #15",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:601] uses only the leaf filename from Windows-style sandbox-validated media paths",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:601",
               "upstream it() block #16",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:613] resolves home-relative local media paths through allowed local roots",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:613",
               "upstream it() block #17",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:624] allows validated host-read TXT files",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:624",
               "upstream it() block #18",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:637] rejects host-read LOG files even though they map to text/plain",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:637",
               "upstream it() block #19",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:652] rejects renamed host-read text files even when the extension looks allowed",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:652",
               "upstream it() block #20",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:666] allows host-read CSV files",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:666",
               "upstream it() block #21",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:679] allows host-read Markdown files",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:679",
               "upstream it() block #22",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:692] allows trusted generated host-read HTML reports under OpenClaw temp root",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:692",
               "upstream it() block #23",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:705] rejects host-read HTML files outside the trusted OpenClaw temp root",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:705",
               "upstream it() block #24",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:724] rejects trusted host-read HTML symlinks that resolve outside OpenClaw temp root",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:724",
               "upstream it() block #25",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:758] rejects trusted host-read HTML hardlinks to files outside OpenClaw temp root",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:758",
               "upstream it() block #26",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:794] rejects trusted host-read HTML paths without HTML document shape",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:794",
               "upstream it() block #27",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:861] rejects binary data disguised as a CSV file",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:861",
               "upstream it() block #28",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1066] rejects traversal-style canvas media paths before filesystem access",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1066",
               "upstream it() block #29",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1073] hydrates inbound media store URIs before allowed-root checks",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1073",
               "upstream it() block #30",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1092] accepts legacy MEDIA prefixes around inbound media store URIs",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1092",
               "upstream it() block #31",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1111] allows managed inbound absolute paths before allowed-root checks",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1111",
               "upstream it() block #32",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1131] applies the shared remote read idle timeout for raw web media loads",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1131",
               "upstream it() block #33",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1147] loads a valid remote PDF when the raw web media read stays active",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1147",
               "upstream it() block #34",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1168] rejects unsupported media store URI locations",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1168",
               "upstream it() block #35",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1175] rejects media store URI ids with encoded path separators",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1175",
               "upstream it() block #36",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/media/web-media.test.ts:1182] rejects media store URIs without an id",
          "[v7_1][parity_gap][media]") {
    PARITY_GAP("src/media/web-media.test.ts:1182",
               "upstream it() block #37",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
