// v2026.4.29 OpenClaw parity mirror of src/cli/daemon-cli.coverage.test.ts
//
// Auto-generated by tests/v4_29/generate.py from the openclaw v2026.4.29
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HAND_AUTHORED sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v4.29 [src/cli/daemon-cli.coverage.test.ts] probes gateway status by default",
          "[v4_29][parity_gap][cli]") {
    PARITY_GAP("src/cli/daemon-cli.coverage.test.ts:176",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cli/daemon-cli.coverage.test.ts] derives probe URL from service args + env (json)",
          "[v4_29][parity_gap][cli]") {
    PARITY_GAP("src/cli/daemon-cli.coverage.test.ts:190",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cli/daemon-cli.coverage.test.ts] passes deep scan flag for daemon status",
          "[v4_29][parity_gap][cli]") {
    PARITY_GAP("src/cli/daemon-cli.coverage.test.ts:228",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cli/daemon-cli.coverage.test.ts] installs the daemon (json output)",
          "[v4_29][parity_gap][cli]") {
    PARITY_GAP("src/cli/daemon-cli.coverage.test.ts:239",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cli/daemon-cli.coverage.test.ts] passes the existing service environment into the install plan on forced reinstall",
          "[v4_29][parity_gap][cli]") {
    PARITY_GAP("src/cli/daemon-cli.coverage.test.ts:265",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cli/daemon-cli.coverage.test.ts] passes an explicit service wrapper into the install plan",
          "[v4_29][parity_gap][cli]") {
    PARITY_GAP("src/cli/daemon-cli.coverage.test.ts:296",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v4.29 [src/cli/daemon-cli.coverage.test.ts] starts and stops daemon (json output)",
          "[v4_29][parity_gap][cli]") {
    PARITY_GAP("src/cli/daemon-cli.coverage.test.ts:315",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
