// v2026.7.1 OpenClaw parity mirror of src/config/config.tools-alsoAllow.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/config/config.tools-alsoAllow.test.ts:8] rejects tools.allow + tools.alsoAllow together",
          "[v7_1][parity_gap][config]") {
    PARITY_GAP("src/config/config.tools-alsoAllow.test.ts:8",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/config/config.tools-alsoAllow.test.ts:22] rejects agents.list[].tools.allow + alsoAllow together",
          "[v7_1][parity_gap][config]") {
    PARITY_GAP("src/config/config.tools-alsoAllow.test.ts:22",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/config/config.tools-alsoAllow.test.ts:43] allows profile + alsoAllow",
          "[v7_1][parity_gap][config]") {
    PARITY_GAP("src/config/config.tools-alsoAllow.test.ts:43",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/config/config.tools-alsoAllow.test.ts:54] allows per-agent message tool cross-context policy",
          "[v7_1][parity_gap][config]") {
    PARITY_GAP("src/config/config.tools-alsoAllow.test.ts:54",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/config/config.tools-alsoAllow.test.ts:76] allows per-agent message tool action allowlists",
          "[v7_1][parity_gap][config]") {
    PARITY_GAP("src/config/config.tools-alsoAllow.test.ts:76",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
