// v2026.5.2 OpenClaw parity mirror of src/commands/models/list.status.test.ts
//
// Auto-generated by tests/v5_2/generate.py from the openclaw v2026.5.2
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:309] includes masked auth sources in JSON output",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:309",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:365] uses agent overrides and reports sources",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:365",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:399] does not double-prefix provider-qualified resolved default models",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:399",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:426] handles cli backend and aliased provider auth summaries",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:426",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:488] treats plugin-owned synthetic auth as usable for models in use",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:488",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:571] includes auth-evidence-only providers in the auth overview",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:571",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:626] reports defaults source when --agent has no overrides",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:626",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:652] throws when agent id is unknown",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:652",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v5.2 [src/commands/models/list.status.test.ts:658] exits non-zero when auth is missing",
          "[v5_2][parity_gap][commands]") {
    PARITY_GAP("src/commands/models/list.status.test.ts:658",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
