// v2026.7.1 OpenClaw parity mirror of packages/acp-core/src/session-interaction-mode.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../parity.hpp"

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:12] returns interactive when entry is undefined",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:12",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:16] returns parent-owned-background for persistent sessions with spawnedBy set",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:16",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:25] returns interactive for persistent ACP sessions without parent linkage",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:25",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:33] returns parent-owned-background for oneshot sessions with spawnedBy set",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:33",
               "upstream it() block #3",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:42] returns parent-owned-background for oneshot sessions with parentSessionKey set",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:42",
               "upstream it() block #4",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:51] returns interactive for a oneshot session without any parent linkage",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:51",
               "upstream it() block #5",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:67] returns true when requester matches spawnedBy",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:67",
               "upstream it() block #6",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:76] returns true when requester matches parentSessionKey",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:76",
               "upstream it() block #7",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:85] returns false when requester is a different session (not the parent)",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:85",
               "upstream it() block #8",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:89] returns false when requester key is missing",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:89",
               "upstream it() block #9",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:94] returns true when target is parent-owned persistent ACP session",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:94",
               "upstream it() block #10",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [packages/acp-core/src/session-interaction-mode.test.ts:103] delegates to isParentOwnedBackgroundAcpSession for target-only checks",
          "[v7_1][parity_gap][acp-core]") {
    PARITY_GAP("packages/acp-core/src/session-interaction-mode.test.ts:103",
               "upstream it() block #11",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
