// v2026.7.1 OpenClaw parity mirror of ui/src/pages/chat/chat-avatar.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../../../parity.hpp"

TEST_CASE("v7.1 [ui/src/pages/chat/chat-avatar.test.ts:16] renders assistant fallback, blob image, and text avatars",
          "[v7_1][parity_gap]") {
    PARITY_GAP("ui/src/pages/chat/chat-avatar.test.ts:16",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [ui/src/pages/chat/chat-avatar.test.ts:36] uses the assistant fallback while authenticated avatar routes are loading",
          "[v7_1][parity_gap]") {
    PARITY_GAP("ui/src/pages/chat/chat-avatar.test.ts:36",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [ui/src/pages/chat/chat-avatar.test.ts:48] renders local user image and text avatars",
          "[v7_1][parity_gap]") {
    PARITY_GAP("ui/src/pages/chat/chat-avatar.test.ts:48",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
