// v2026.7.1 OpenClaw parity mirror of src/secrets/provider-env-vars.test.ts
//
// Auto-generated by tests/v7_1/generate.py from the openclaw v2026.7.1
// submodule. Each TEST_CASE corresponds to an upstream it()/test() block;
// the body PARITY_GAP()s with a precise upstream file:line reference.
//
// To convert a gap into a real test, replace the PARITY_GAP body with
// behavioral assertions and add the // MYLOBSTERPP_HANDWRITTEN_TEST sentinel
// near the top of the file. The generator will then leave it alone.

#include "../../parity.hpp"

TEST_CASE("v7.1 [src/secrets/provider-env-vars.test.ts:11] keeps the auth scrub list broader than the global secret env list",
          "[v7_1][parity_gap][secrets]") {
    PARITY_GAP("src/secrets/provider-env-vars.test.ts:11",
               "upstream it() block #0",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/secrets/provider-env-vars.test.ts:41] omits env keys case-insensitively",
          "[v7_1][parity_gap][secrets]") {
    PARITY_GAP("src/secrets/provider-env-vars.test.ts:41",
               "upstream it() block #1",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}

TEST_CASE("v7.1 [src/secrets/provider-env-vars.test.ts:56] ignores prototype-chain keys when resolving provider env vars",
          "[v7_1][parity_gap][secrets]") {
    PARITY_GAP("src/secrets/provider-env-vars.test.ts:56",
               "upstream it() block #2",
               "Auto-generated parity gap; replace with real assertion when mylobsterpp grows the upstream abstraction.");
}
